services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/howwastheweather
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=1234
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: src/main/frontend  # Path to frontend directory
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    environment:
    - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=howwastheweather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: